spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: Ticket-Flow
          uri: ${TICKETFLOW_ROUTE_URL}
          predicates:
            - Path=/**


server:
  port: 1212

jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}


gateway:
  secret: ${GATEWAY_SECRET}