spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: TicketFlow

  # Database Setting
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver

  # Jpa Setting
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

  # redis Setting
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: 9090


jwt:
  secret:
    access: ${JWT_ACCESS_SECRET}
    refresh: ${JWT_REFRESH_SECRET}

gateway:
  secret: ${GATEWAY_SECRET}